name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
        JWT_APP_SECRET: ${{ secrets.JWT_APP_SECRET }}
        SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        RESET_SECRET: ${{ secrets.RESET_SECRET }}
        SENDGRID_SEND_EMAIL: ${{ secrets.SENDGRID_SEND_EMAIL }}
        CLIENT_URL_PW_RESET: ${{ secrets.CLIENT_URL_PW_RESET }}
        TEST_USER_EMAIL_1: ${{ secrets.TEST_USER_EMAIL_1 }}
        TEST_USER_EMAIL_2: ${{ secrets.TEST_USER_EMAIL_2 }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_ACCESS_REGION: ${{ secrets.AWS_ACCESS_REGION }}
        AWS_FROM_EMAIL: ${{ secrets.AWS_FROM_EMAIL }}
